# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryption_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='encryption_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x65ncryption_service.proto\"!\n\x0e\x45ncryptRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0f\x45ncryptResponse\x12\x0e\n\x06\x63ipher\x18\x01 \x01(\t\" \n\x0e\x44\x65\x63ryptRequest\x12\x0e\n\x06\x63ipher\x18\x01 \x01(\t\"\"\n\x0f\x44\x65\x63ryptResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2o\n\x11\x45ncryptionService\x12,\n\x07\x45ncrypt\x12\x0f.EncryptRequest\x1a\x10.EncryptResponse\x12,\n\x07\x44\x65\x63rypt\x12\x0f.DecryptRequest\x1a\x10.DecryptResponseb\x06proto3'
)




_ENCRYPTREQUEST = _descriptor.Descriptor(
  name='EncryptRequest',
  full_name='EncryptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='EncryptRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=61,
)


_ENCRYPTRESPONSE = _descriptor.Descriptor(
  name='EncryptResponse',
  full_name='EncryptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cipher', full_name='EncryptResponse.cipher', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=96,
)


_DECRYPTREQUEST = _descriptor.Descriptor(
  name='DecryptRequest',
  full_name='DecryptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cipher', full_name='DecryptRequest.cipher', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=130,
)


_DECRYPTRESPONSE = _descriptor.Descriptor(
  name='DecryptResponse',
  full_name='DecryptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='DecryptResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=166,
)

DESCRIPTOR.message_types_by_name['EncryptRequest'] = _ENCRYPTREQUEST
DESCRIPTOR.message_types_by_name['EncryptResponse'] = _ENCRYPTRESPONSE
DESCRIPTOR.message_types_by_name['DecryptRequest'] = _DECRYPTREQUEST
DESCRIPTOR.message_types_by_name['DecryptResponse'] = _DECRYPTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EncryptRequest = _reflection.GeneratedProtocolMessageType('EncryptRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTREQUEST,
  '__module__' : 'encryption_service_pb2'
  # @@protoc_insertion_point(class_scope:EncryptRequest)
  })
_sym_db.RegisterMessage(EncryptRequest)

EncryptResponse = _reflection.GeneratedProtocolMessageType('EncryptResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTRESPONSE,
  '__module__' : 'encryption_service_pb2'
  # @@protoc_insertion_point(class_scope:EncryptResponse)
  })
_sym_db.RegisterMessage(EncryptResponse)

DecryptRequest = _reflection.GeneratedProtocolMessageType('DecryptRequest', (_message.Message,), {
  'DESCRIPTOR' : _DECRYPTREQUEST,
  '__module__' : 'encryption_service_pb2'
  # @@protoc_insertion_point(class_scope:DecryptRequest)
  })
_sym_db.RegisterMessage(DecryptRequest)

DecryptResponse = _reflection.GeneratedProtocolMessageType('DecryptResponse', (_message.Message,), {
  'DESCRIPTOR' : _DECRYPTRESPONSE,
  '__module__' : 'encryption_service_pb2'
  # @@protoc_insertion_point(class_scope:DecryptResponse)
  })
_sym_db.RegisterMessage(DecryptResponse)



_ENCRYPTIONSERVICE = _descriptor.ServiceDescriptor(
  name='EncryptionService',
  full_name='EncryptionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=168,
  serialized_end=279,
  methods=[
  _descriptor.MethodDescriptor(
    name='Encrypt',
    full_name='EncryptionService.Encrypt',
    index=0,
    containing_service=None,
    input_type=_ENCRYPTREQUEST,
    output_type=_ENCRYPTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Decrypt',
    full_name='EncryptionService.Decrypt',
    index=1,
    containing_service=None,
    input_type=_DECRYPTREQUEST,
    output_type=_DECRYPTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENCRYPTIONSERVICE)

DESCRIPTOR.services_by_name['EncryptionService'] = _ENCRYPTIONSERVICE

# @@protoc_insertion_point(module_scope)
