version: "3.9"
services:
    encryptionservice:
        build: ../Services/EncryptionService
        image: sasuuu/przyjaznybot:encryptionservice
        container_name: przyjaznybot-encryptionservice
        restart: unless-stopped
        ports:
            - "50051:50051"
        volumes:
            - encryptionservice-data:/app/data
    postgres:
        image: postgres
        container_name: przyjaznybot-postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    userservice:
        build: ../Services/UserService
        image: sasuuu/przyjaznybot:userservice
        container_name: przyjaznybot-userservice
        restart: unless-stopped
        environment:
            DbHost: przyjaznybot-postgres
            DbDatabase: przyjaznybotdb
            DbUsername: postgres
            DbPassword: gAAAAABiF-ehAN55tP2qt0YcnLYZbsrlgEMBT9Q0MlViiSClT9XVDVqaF1Z4wrIskYo47n3AOYdkBnkj5LnhbYuvJZo9TCxSKUVmYxTLNSVMS1QP4dx-shY=
            EncryptionServiceAddress: http://przyjaznybot-encryptionservice:50051
        ports:
            - "50052:80"
        depends_on:
            - postgres
            - encryptionservice
    betservice:
        build: ../Services/BetService
        image: sasuuu/przyjaznybot:betservice
        container_name: przyjaznybot-betservice
        restart: unless-stopped
        environment:
            DbHost: przyjaznybot-postgres
            DbDatabase: przyjaznybotdb
            DbUsername: postgres
            DbPassword: gAAAAABiF-ehAN55tP2qt0YcnLYZbsrlgEMBT9Q0MlViiSClT9XVDVqaF1Z4wrIskYo47n3AOYdkBnkj5LnhbYuvJZo9TCxSKUVmYxTLNSVMS1QP4dx-shY=
            EncryptionServiceAddress: http://przyjaznybot-encryptionservice:50051
            UserServiceAddress: http://przyjaznybot-encryptionservice:50052
        ports:
            - "50053:80"
        depends_on:
            - postgres
            - encryptionservice
            - userservice

volumes:
    encryptionservice-data:
    postgres-data: