version: "3.9"
services:
    encryptionservice:
        build: ../Services/EncryptionService
        image: sasuuu/przyjaznybot:encryptionservice
        container_name: przyjaznybot-encryptionservice
        restart: unless-stopped
        ports:
            - "50051:50051"
        volumes:
            - przyjaznybot-encryptionservice-data:/app/data
    postgres:
        image: postgres
        container_name: przyjaznybot-postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: przyjaznybot2137
        ports:
            - "5432:5432"
        volumes:
            - przyjaznybot-postgres-data:/var/lib/postgresql/data

volumes:
    przyjaznybot-encryptionservice-data:
    przyjaznybot-postgres-data: